name: formation_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.7 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  
  intl: any

  # UI
  flutter_svg: ^2.2.3
  # Ajout de Provider ici
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # J'ai remis une version compatible avec votre SDK
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - res/drawables/
    - res/svg/

  fonts:
    - family: AppIcons
      fonts:
        - asset: res/fonts/app_icons.ttf
    - family: Avenir
      fonts:
        - asset: res/fonts/Avenir-Light.ttf
          weight: 300
        - asset: res/fonts/Avenir-Regular.ttf
          weight: 400
        - asset: res/fonts/Avenir-Medium.ttf
          weight: 500
        - asset: res/fonts/Avenir-Black.ttf
          weight: 900

  generate: true